// Code generated by protoc-gen-go. DO NOT EDIT.
// source: variflight.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VariFlightData struct {
	Fcategory             string   `protobuf:"bytes,1,opt,name=fcategory,proto3" json:"fcategory,omitempty"`
	FlightNo              string   `protobuf:"bytes,2,opt,name=FlightNo,proto3" json:"FlightNo,omitempty"`
	FlightCompany         string   `protobuf:"bytes,3,opt,name=FlightCompany,proto3" json:"FlightCompany,omitempty"`
	FlightDepcode         string   `protobuf:"bytes,4,opt,name=FlightDepcode,proto3" json:"FlightDepcode,omitempty"`
	FlightArrcode         string   `protobuf:"bytes,5,opt,name=FlightArrcode,proto3" json:"FlightArrcode,omitempty"`
	FlightDeptimePlanDate string   `protobuf:"bytes,6,opt,name=FlightDeptimePlanDate,proto3" json:"FlightDeptimePlanDate,omitempty"`
	FlightArrtimePlanDate string   `protobuf:"bytes,7,opt,name=FlightArrtimePlanDate,proto3" json:"FlightArrtimePlanDate,omitempty"`
	FlightDeptimeDate     string   `protobuf:"bytes,8,opt,name=FlightDeptimeDate,proto3" json:"FlightDeptimeDate,omitempty"`
	FlightArrtimeDate     string   `protobuf:"bytes,9,opt,name=FlightArrtimeDate,proto3" json:"FlightArrtimeDate,omitempty"`
	FlightState           string   `protobuf:"bytes,10,opt,name=FlightState,proto3" json:"FlightState,omitempty"`
	FlightHTerminal       string   `protobuf:"bytes,11,opt,name=FlightHTerminal,proto3" json:"FlightHTerminal,omitempty"`
	FlightTerminal        string   `protobuf:"bytes,12,opt,name=FlightTerminal,proto3" json:"FlightTerminal,omitempty"`
	OrgTimezone           string   `protobuf:"bytes,13,opt,name=org_timezone,json=orgTimezone,proto3" json:"org_timezone,omitempty"`
	DstTimezone           string   `protobuf:"bytes,14,opt,name=dst_timezone,json=dstTimezone,proto3" json:"dst_timezone,omitempty"`
	ShareFlightNo         string   `protobuf:"bytes,15,opt,name=ShareFlightNo,proto3" json:"ShareFlightNo,omitempty"`
	StopFlag              string   `protobuf:"bytes,16,opt,name=StopFlag,proto3" json:"StopFlag,omitempty"`
	ShareFlag             string   `protobuf:"bytes,17,opt,name=ShareFlag,proto3" json:"ShareFlag,omitempty"`
	VirtualFlag           string   `protobuf:"bytes,18,opt,name=VirtualFlag,proto3" json:"VirtualFlag,omitempty"`
	LegFlag               string   `protobuf:"bytes,19,opt,name=LegFlag,proto3" json:"LegFlag,omitempty"`
	FlightDep             string   `protobuf:"bytes,20,opt,name=FlightDep,proto3" json:"FlightDep,omitempty"`
	FlightArr             string   `protobuf:"bytes,21,opt,name=FlightArr,proto3" json:"FlightArr,omitempty"`
	FlightDepAirport      string   `protobuf:"bytes,22,opt,name=FlightDepAirport,proto3" json:"FlightDepAirport,omitempty"`
	FlightArrAirport      string   `protobuf:"bytes,23,opt,name=FlightArrAirport,proto3" json:"FlightArrAirport,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *VariFlightData) Reset()         { *m = VariFlightData{} }
func (m *VariFlightData) String() string { return proto.CompactTextString(m) }
func (*VariFlightData) ProtoMessage()    {}
func (*VariFlightData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b7cf0666aebe7ef, []int{0}
}

func (m *VariFlightData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VariFlightData.Unmarshal(m, b)
}
func (m *VariFlightData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VariFlightData.Marshal(b, m, deterministic)
}
func (m *VariFlightData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VariFlightData.Merge(m, src)
}
func (m *VariFlightData) XXX_Size() int {
	return xxx_messageInfo_VariFlightData.Size(m)
}
func (m *VariFlightData) XXX_DiscardUnknown() {
	xxx_messageInfo_VariFlightData.DiscardUnknown(m)
}

var xxx_messageInfo_VariFlightData proto.InternalMessageInfo

func (m *VariFlightData) GetFcategory() string {
	if m != nil {
		return m.Fcategory
	}
	return ""
}

func (m *VariFlightData) GetFlightNo() string {
	if m != nil {
		return m.FlightNo
	}
	return ""
}

func (m *VariFlightData) GetFlightCompany() string {
	if m != nil {
		return m.FlightCompany
	}
	return ""
}

func (m *VariFlightData) GetFlightDepcode() string {
	if m != nil {
		return m.FlightDepcode
	}
	return ""
}

func (m *VariFlightData) GetFlightArrcode() string {
	if m != nil {
		return m.FlightArrcode
	}
	return ""
}

func (m *VariFlightData) GetFlightDeptimePlanDate() string {
	if m != nil {
		return m.FlightDeptimePlanDate
	}
	return ""
}

func (m *VariFlightData) GetFlightArrtimePlanDate() string {
	if m != nil {
		return m.FlightArrtimePlanDate
	}
	return ""
}

func (m *VariFlightData) GetFlightDeptimeDate() string {
	if m != nil {
		return m.FlightDeptimeDate
	}
	return ""
}

func (m *VariFlightData) GetFlightArrtimeDate() string {
	if m != nil {
		return m.FlightArrtimeDate
	}
	return ""
}

func (m *VariFlightData) GetFlightState() string {
	if m != nil {
		return m.FlightState
	}
	return ""
}

func (m *VariFlightData) GetFlightHTerminal() string {
	if m != nil {
		return m.FlightHTerminal
	}
	return ""
}

func (m *VariFlightData) GetFlightTerminal() string {
	if m != nil {
		return m.FlightTerminal
	}
	return ""
}

func (m *VariFlightData) GetOrgTimezone() string {
	if m != nil {
		return m.OrgTimezone
	}
	return ""
}

func (m *VariFlightData) GetDstTimezone() string {
	if m != nil {
		return m.DstTimezone
	}
	return ""
}

func (m *VariFlightData) GetShareFlightNo() string {
	if m != nil {
		return m.ShareFlightNo
	}
	return ""
}

func (m *VariFlightData) GetStopFlag() string {
	if m != nil {
		return m.StopFlag
	}
	return ""
}

func (m *VariFlightData) GetShareFlag() string {
	if m != nil {
		return m.ShareFlag
	}
	return ""
}

func (m *VariFlightData) GetVirtualFlag() string {
	if m != nil {
		return m.VirtualFlag
	}
	return ""
}

func (m *VariFlightData) GetLegFlag() string {
	if m != nil {
		return m.LegFlag
	}
	return ""
}

func (m *VariFlightData) GetFlightDep() string {
	if m != nil {
		return m.FlightDep
	}
	return ""
}

func (m *VariFlightData) GetFlightArr() string {
	if m != nil {
		return m.FlightArr
	}
	return ""
}

func (m *VariFlightData) GetFlightDepAirport() string {
	if m != nil {
		return m.FlightDepAirport
	}
	return ""
}

func (m *VariFlightData) GetFlightArrAirport() string {
	if m != nil {
		return m.FlightArrAirport
	}
	return ""
}

type GetFlightDataByFlightNumberRequest struct {
	FlightNumber         string   `protobuf:"bytes,1,opt,name=flightNumber,proto3" json:"flightNumber,omitempty"`
	Date                 string   `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFlightDataByFlightNumberRequest) Reset()         { *m = GetFlightDataByFlightNumberRequest{} }
func (m *GetFlightDataByFlightNumberRequest) String() string { return proto.CompactTextString(m) }
func (*GetFlightDataByFlightNumberRequest) ProtoMessage()    {}
func (*GetFlightDataByFlightNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b7cf0666aebe7ef, []int{1}
}

func (m *GetFlightDataByFlightNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFlightDataByFlightNumberRequest.Unmarshal(m, b)
}
func (m *GetFlightDataByFlightNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFlightDataByFlightNumberRequest.Marshal(b, m, deterministic)
}
func (m *GetFlightDataByFlightNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFlightDataByFlightNumberRequest.Merge(m, src)
}
func (m *GetFlightDataByFlightNumberRequest) XXX_Size() int {
	return xxx_messageInfo_GetFlightDataByFlightNumberRequest.Size(m)
}
func (m *GetFlightDataByFlightNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFlightDataByFlightNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFlightDataByFlightNumberRequest proto.InternalMessageInfo

func (m *GetFlightDataByFlightNumberRequest) GetFlightNumber() string {
	if m != nil {
		return m.FlightNumber
	}
	return ""
}

func (m *GetFlightDataByFlightNumberRequest) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type GetFlightDataBetweenTwoAirportsRequest struct {
	DepartureAirport     string   `protobuf:"bytes,1,opt,name=departureAirport,proto3" json:"departureAirport,omitempty"`
	ArrivalAirport       string   `protobuf:"bytes,2,opt,name=arrivalAirport,proto3" json:"arrivalAirport,omitempty"`
	Date                 string   `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFlightDataBetweenTwoAirportsRequest) Reset() {
	*m = GetFlightDataBetweenTwoAirportsRequest{}
}
func (m *GetFlightDataBetweenTwoAirportsRequest) String() string { return proto.CompactTextString(m) }
func (*GetFlightDataBetweenTwoAirportsRequest) ProtoMessage()    {}
func (*GetFlightDataBetweenTwoAirportsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b7cf0666aebe7ef, []int{2}
}

func (m *GetFlightDataBetweenTwoAirportsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFlightDataBetweenTwoAirportsRequest.Unmarshal(m, b)
}
func (m *GetFlightDataBetweenTwoAirportsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFlightDataBetweenTwoAirportsRequest.Marshal(b, m, deterministic)
}
func (m *GetFlightDataBetweenTwoAirportsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFlightDataBetweenTwoAirportsRequest.Merge(m, src)
}
func (m *GetFlightDataBetweenTwoAirportsRequest) XXX_Size() int {
	return xxx_messageInfo_GetFlightDataBetweenTwoAirportsRequest.Size(m)
}
func (m *GetFlightDataBetweenTwoAirportsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFlightDataBetweenTwoAirportsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFlightDataBetweenTwoAirportsRequest proto.InternalMessageInfo

func (m *GetFlightDataBetweenTwoAirportsRequest) GetDepartureAirport() string {
	if m != nil {
		return m.DepartureAirport
	}
	return ""
}

func (m *GetFlightDataBetweenTwoAirportsRequest) GetArrivalAirport() string {
	if m != nil {
		return m.ArrivalAirport
	}
	return ""
}

func (m *GetFlightDataBetweenTwoAirportsRequest) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type GetFlightDataBetweenTwoCitiesRequest struct {
	DepartureCity        string   `protobuf:"bytes,1,opt,name=departureCity,proto3" json:"departureCity,omitempty"`
	ArrivalCity          string   `protobuf:"bytes,2,opt,name=arrivalCity,proto3" json:"arrivalCity,omitempty"`
	Date                 string   `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFlightDataBetweenTwoCitiesRequest) Reset()         { *m = GetFlightDataBetweenTwoCitiesRequest{} }
func (m *GetFlightDataBetweenTwoCitiesRequest) String() string { return proto.CompactTextString(m) }
func (*GetFlightDataBetweenTwoCitiesRequest) ProtoMessage()    {}
func (*GetFlightDataBetweenTwoCitiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b7cf0666aebe7ef, []int{3}
}

func (m *GetFlightDataBetweenTwoCitiesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFlightDataBetweenTwoCitiesRequest.Unmarshal(m, b)
}
func (m *GetFlightDataBetweenTwoCitiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFlightDataBetweenTwoCitiesRequest.Marshal(b, m, deterministic)
}
func (m *GetFlightDataBetweenTwoCitiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFlightDataBetweenTwoCitiesRequest.Merge(m, src)
}
func (m *GetFlightDataBetweenTwoCitiesRequest) XXX_Size() int {
	return xxx_messageInfo_GetFlightDataBetweenTwoCitiesRequest.Size(m)
}
func (m *GetFlightDataBetweenTwoCitiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFlightDataBetweenTwoCitiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFlightDataBetweenTwoCitiesRequest proto.InternalMessageInfo

func (m *GetFlightDataBetweenTwoCitiesRequest) GetDepartureCity() string {
	if m != nil {
		return m.DepartureCity
	}
	return ""
}

func (m *GetFlightDataBetweenTwoCitiesRequest) GetArrivalCity() string {
	if m != nil {
		return m.ArrivalCity
	}
	return ""
}

func (m *GetFlightDataBetweenTwoCitiesRequest) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type GetFlightDataAtOneAirportByStatusRequest struct {
	Airport              string   `protobuf:"bytes,1,opt,name=airport,proto3" json:"airport,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Date                 string   `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFlightDataAtOneAirportByStatusRequest) Reset() {
	*m = GetFlightDataAtOneAirportByStatusRequest{}
}
func (m *GetFlightDataAtOneAirportByStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetFlightDataAtOneAirportByStatusRequest) ProtoMessage()    {}
func (*GetFlightDataAtOneAirportByStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b7cf0666aebe7ef, []int{4}
}

func (m *GetFlightDataAtOneAirportByStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFlightDataAtOneAirportByStatusRequest.Unmarshal(m, b)
}
func (m *GetFlightDataAtOneAirportByStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFlightDataAtOneAirportByStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetFlightDataAtOneAirportByStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFlightDataAtOneAirportByStatusRequest.Merge(m, src)
}
func (m *GetFlightDataAtOneAirportByStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetFlightDataAtOneAirportByStatusRequest.Size(m)
}
func (m *GetFlightDataAtOneAirportByStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFlightDataAtOneAirportByStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFlightDataAtOneAirportByStatusRequest proto.InternalMessageInfo

func (m *GetFlightDataAtOneAirportByStatusRequest) GetAirport() string {
	if m != nil {
		return m.Airport
	}
	return ""
}

func (m *GetFlightDataAtOneAirportByStatusRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetFlightDataAtOneAirportByStatusRequest) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func init() {
	proto.RegisterType((*VariFlightData)(nil), "protobuf.VariFlightData")
	proto.RegisterType((*GetFlightDataByFlightNumberRequest)(nil), "protobuf.GetFlightDataByFlightNumberRequest")
	proto.RegisterType((*GetFlightDataBetweenTwoAirportsRequest)(nil), "protobuf.GetFlightDataBetweenTwoAirportsRequest")
	proto.RegisterType((*GetFlightDataBetweenTwoCitiesRequest)(nil), "protobuf.GetFlightDataBetweenTwoCitiesRequest")
	proto.RegisterType((*GetFlightDataAtOneAirportByStatusRequest)(nil), "protobuf.GetFlightDataAtOneAirportByStatusRequest")
}

func init() { proto.RegisterFile("variflight.proto", fileDescriptor_0b7cf0666aebe7ef) }

var fileDescriptor_0b7cf0666aebe7ef = []byte{
	// 650 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0xd1, 0x4e, 0xdb, 0x30,
	0x14, 0x86, 0xd7, 0xc1, 0x0a, 0x1c, 0x28, 0x14, 0x6f, 0x30, 0x8b, 0x6d, 0x1a, 0x8b, 0x2a, 0x84,
	0x10, 0xaa, 0x10, 0xdb, 0x0b, 0x04, 0x2a, 0xb6, 0x8b, 0x69, 0x9b, 0x28, 0xe2, 0x6a, 0xd2, 0x64,
	0x88, 0x1b, 0x2c, 0xa5, 0x71, 0x38, 0x75, 0x40, 0x9d, 0x76, 0xb5, 0x27, 0xd8, 0x33, 0xee, 0x01,
	0xf6, 0x0c, 0x53, 0xec, 0xc4, 0xb1, 0x0b, 0x6d, 0xaf, 0x1a, 0xff, 0xe7, 0x3b, 0xfe, 0x4f, 0xe3,
	0xdf, 0x81, 0xf6, 0x1d, 0x43, 0x31, 0x48, 0x44, 0x7c, 0xa3, 0xba, 0x19, 0x4a, 0x25, 0xc9, 0xb2,
	0xfe, 0xb9, 0xca, 0x07, 0xc1, 0xbf, 0x26, 0xac, 0x5f, 0x32, 0x14, 0x67, 0xba, 0xdc, 0x63, 0x8a,
	0x91, 0xd7, 0xb0, 0x32, 0xb8, 0x66, 0x8a, 0xc7, 0x12, 0xc7, 0xb4, 0xb1, 0xdb, 0xd8, 0x5f, 0x39,
	0xaf, 0x05, 0xb2, 0x03, 0xcb, 0x86, 0xfd, 0x22, 0xe9, 0x53, 0x5d, 0xb4, 0x6b, 0xd2, 0x81, 0x96,
	0x79, 0x3e, 0x95, 0xc3, 0x8c, 0xa5, 0x63, 0xba, 0xa0, 0x01, 0x5f, 0xac, 0xa9, 0x1e, 0xcf, 0xae,
	0x65, 0xc4, 0xe9, 0xa2, 0x4b, 0x95, 0x62, 0x4d, 0x85, 0x88, 0x9a, 0x7a, 0xe6, 0x52, 0xa5, 0x48,
	0x3e, 0xc0, 0x96, 0x6d, 0x53, 0x62, 0xc8, 0xbf, 0x25, 0x2c, 0xed, 0x31, 0xc5, 0x69, 0x53, 0xd3,
	0x8f, 0x17, 0xeb, 0xae, 0x10, 0xd1, 0xeb, 0x5a, 0x72, 0xbb, 0x26, 0x8a, 0xe4, 0x10, 0x36, 0xbd,
	0xed, 0x74, 0xc7, 0xb2, 0xee, 0x78, 0x58, 0xa8, 0xe9, 0x72, 0x1b, 0x4d, 0xaf, 0xb8, 0xb4, 0x53,
	0x20, 0xbb, 0xb0, 0x6a, 0xc4, 0xbe, 0x2a, 0x38, 0xd0, 0x9c, 0x2b, 0x91, 0x7d, 0xd8, 0x30, 0xcb,
	0x4f, 0x17, 0x1c, 0x87, 0x22, 0x65, 0x09, 0x5d, 0xd5, 0xd4, 0xa4, 0x4c, 0xf6, 0x60, 0xdd, 0x48,
	0x16, 0x5c, 0xd3, 0xe0, 0x84, 0x4a, 0xde, 0xc1, 0x9a, 0xc4, 0xf8, 0x47, 0x31, 0xc3, 0x4f, 0x99,
	0x72, 0xda, 0x32, 0xa6, 0x12, 0xe3, 0x8b, 0x52, 0x2a, 0x90, 0x68, 0xa4, 0x6a, 0x64, 0xdd, 0x20,
	0xd1, 0x48, 0x59, 0xa4, 0x03, 0xad, 0xfe, 0x0d, 0x43, 0x6e, 0x43, 0xb1, 0x61, 0xce, 0xc9, 0x13,
	0x8b, 0xd4, 0xf4, 0x95, 0xcc, 0xce, 0x12, 0x16, 0xd3, 0xb6, 0x49, 0x4d, 0xb5, 0x2e, 0xf2, 0x56,
	0xc2, 0x2c, 0xa6, 0x9b, 0x26, 0x6f, 0x56, 0x28, 0xde, 0xcc, 0xa5, 0x40, 0x95, 0xb3, 0x44, 0xd7,
	0x89, 0x99, 0xc0, 0x91, 0x08, 0x85, 0xa5, 0xcf, 0x3c, 0xd6, 0xd5, 0xe7, 0xba, 0x5a, 0x2d, 0x8b,
	0x9d, 0xed, 0xc1, 0xd0, 0x17, 0x66, 0x67, 0x2b, 0xd4, 0xd5, 0x10, 0x91, 0x6e, 0xb9, 0xd5, 0x10,
	0x91, 0x1c, 0x40, 0xdb, 0xa2, 0xa1, 0xc0, 0x4c, 0xa2, 0xa2, 0xdb, 0x1a, 0x7a, 0xa0, 0xd7, 0x6c,
	0x88, 0x58, 0xb1, 0x2f, 0x5d, 0xb6, 0xd6, 0x83, 0xef, 0x10, 0x7c, 0xe4, 0xaa, 0xbe, 0x6e, 0x27,
	0xe3, 0xf2, 0x25, 0xe5, 0xc3, 0x2b, 0x8e, 0xe7, 0xfc, 0x36, 0xe7, 0x23, 0x45, 0x02, 0x58, 0x1b,
	0x38, 0x72, 0x79, 0x0d, 0x3d, 0x8d, 0x10, 0x58, 0x8c, 0x8a, 0xb0, 0x98, 0x5b, 0xa8, 0x9f, 0x83,
	0x3f, 0x0d, 0xd8, 0xf3, 0xb7, 0xe7, 0xea, 0x9e, 0xf3, 0xf4, 0xe2, 0x5e, 0x96, 0x03, 0x8c, 0x2a,
	0x8b, 0x03, 0x68, 0x47, 0x3c, 0x63, 0xa8, 0x72, 0xe4, 0xd5, 0xd0, 0xc6, 0xe6, 0x81, 0x5e, 0x44,
	0x8a, 0x21, 0x8a, 0x3b, 0x96, 0x54, 0xa4, 0x31, 0x9d, 0x50, 0xed, 0x48, 0x0b, 0xce, 0x48, 0xbf,
	0x1b, 0xd0, 0x99, 0x32, 0xd2, 0xa9, 0x50, 0x82, 0xdb, 0x81, 0x3a, 0xd0, 0xb2, 0xc6, 0xa7, 0x42,
	0x55, 0xdf, 0x1e, 0x5f, 0x2c, 0xf2, 0x50, 0x9a, 0x6a, 0xc6, 0xcc, 0xe1, 0x4a, 0x8f, 0x0e, 0x91,
	0xc1, 0xbe, 0x37, 0x43, 0xa8, 0xbe, 0xa6, 0xd5, 0xbf, 0x3b, 0x19, 0x17, 0x37, 0x2c, 0xb7, 0x73,
	0x50, 0x58, 0x62, 0xde, 0xfb, 0xa8, 0x96, 0x64, 0x1b, 0x9a, 0x23, 0x8d, 0x96, 0xb6, 0xe5, 0xea,
	0x31, 0xc7, 0xe3, 0xbf, 0x0b, 0xb0, 0xe5, 0x7f, 0x58, 0xfb, 0x1c, 0xef, 0xc4, 0x35, 0x27, 0x02,
	0x5e, 0xcd, 0x48, 0x00, 0x39, 0xec, 0x56, 0x1f, 0xe7, 0xee, 0xfc, 0xa0, 0xec, 0xd0, 0x9a, 0xf6,
	0xdd, 0x82, 0x27, 0x47, 0x0d, 0x72, 0x0b, 0x6f, 0xe7, 0xa4, 0x81, 0x1c, 0x4d, 0xb3, 0x9b, 0x16,
	0x9c, 0x39, 0x96, 0x43, 0x78, 0x33, 0xf3, 0xb4, 0x49, 0x77, 0xae, 0xa1, 0x17, 0x8b, 0x39, 0x76,
	0xbf, 0x26, 0x0e, 0xf6, 0x64, 0xdc, 0xb3, 0xe1, 0x4d, 0xa3, 0xd0, 0xc4, 0xc2, 0x9c, 0x2f, 0x39,
	0x9e, 0xe2, 0x3c, 0x23, 0x0c, 0xb3, 0xdd, 0xaf, 0x9a, 0xba, 0xf8, 0xfe, 0x7f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xf5, 0x07, 0xd9, 0x91, 0x62, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VariFlightDataServiceClient is the client API for VariFlightDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VariFlightDataServiceClient interface {
	GetFlightDataByFlightNumber(ctx context.Context, in *GetFlightDataByFlightNumberRequest, opts ...grpc.CallOption) (VariFlightDataService_GetFlightDataByFlightNumberClient, error)
	GetFlightDataBetweenTwoAirports(ctx context.Context, in *GetFlightDataBetweenTwoAirportsRequest, opts ...grpc.CallOption) (VariFlightDataService_GetFlightDataBetweenTwoAirportsClient, error)
	GetFlightDataBetweenTwoCities(ctx context.Context, in *GetFlightDataBetweenTwoCitiesRequest, opts ...grpc.CallOption) (VariFlightDataService_GetFlightDataBetweenTwoCitiesClient, error)
	GetFlightDataByDepartureAndArrivalStatus(ctx context.Context, in *GetFlightDataAtOneAirportByStatusRequest, opts ...grpc.CallOption) (VariFlightDataService_GetFlightDataByDepartureAndArrivalStatusClient, error)
}

type variFlightDataServiceClient struct {
	cc *grpc.ClientConn
}

func NewVariFlightDataServiceClient(cc *grpc.ClientConn) VariFlightDataServiceClient {
	return &variFlightDataServiceClient{cc}
}

func (c *variFlightDataServiceClient) GetFlightDataByFlightNumber(ctx context.Context, in *GetFlightDataByFlightNumberRequest, opts ...grpc.CallOption) (VariFlightDataService_GetFlightDataByFlightNumberClient, error) {
	stream, err := c.cc.NewStream(ctx, &_VariFlightDataService_serviceDesc.Streams[0], "/protobuf.VariFlightDataService/GetFlightDataByFlightNumber", opts...)
	if err != nil {
		return nil, err
	}
	x := &variFlightDataServiceGetFlightDataByFlightNumberClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VariFlightDataService_GetFlightDataByFlightNumberClient interface {
	Recv() (*VariFlightData, error)
	grpc.ClientStream
}

type variFlightDataServiceGetFlightDataByFlightNumberClient struct {
	grpc.ClientStream
}

func (x *variFlightDataServiceGetFlightDataByFlightNumberClient) Recv() (*VariFlightData, error) {
	m := new(VariFlightData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *variFlightDataServiceClient) GetFlightDataBetweenTwoAirports(ctx context.Context, in *GetFlightDataBetweenTwoAirportsRequest, opts ...grpc.CallOption) (VariFlightDataService_GetFlightDataBetweenTwoAirportsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_VariFlightDataService_serviceDesc.Streams[1], "/protobuf.VariFlightDataService/GetFlightDataBetweenTwoAirports", opts...)
	if err != nil {
		return nil, err
	}
	x := &variFlightDataServiceGetFlightDataBetweenTwoAirportsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VariFlightDataService_GetFlightDataBetweenTwoAirportsClient interface {
	Recv() (*VariFlightData, error)
	grpc.ClientStream
}

type variFlightDataServiceGetFlightDataBetweenTwoAirportsClient struct {
	grpc.ClientStream
}

func (x *variFlightDataServiceGetFlightDataBetweenTwoAirportsClient) Recv() (*VariFlightData, error) {
	m := new(VariFlightData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *variFlightDataServiceClient) GetFlightDataBetweenTwoCities(ctx context.Context, in *GetFlightDataBetweenTwoCitiesRequest, opts ...grpc.CallOption) (VariFlightDataService_GetFlightDataBetweenTwoCitiesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_VariFlightDataService_serviceDesc.Streams[2], "/protobuf.VariFlightDataService/GetFlightDataBetweenTwoCities", opts...)
	if err != nil {
		return nil, err
	}
	x := &variFlightDataServiceGetFlightDataBetweenTwoCitiesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VariFlightDataService_GetFlightDataBetweenTwoCitiesClient interface {
	Recv() (*VariFlightData, error)
	grpc.ClientStream
}

type variFlightDataServiceGetFlightDataBetweenTwoCitiesClient struct {
	grpc.ClientStream
}

func (x *variFlightDataServiceGetFlightDataBetweenTwoCitiesClient) Recv() (*VariFlightData, error) {
	m := new(VariFlightData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *variFlightDataServiceClient) GetFlightDataByDepartureAndArrivalStatus(ctx context.Context, in *GetFlightDataAtOneAirportByStatusRequest, opts ...grpc.CallOption) (VariFlightDataService_GetFlightDataByDepartureAndArrivalStatusClient, error) {
	stream, err := c.cc.NewStream(ctx, &_VariFlightDataService_serviceDesc.Streams[3], "/protobuf.VariFlightDataService/GetFlightDataByDepartureAndArrivalStatus", opts...)
	if err != nil {
		return nil, err
	}
	x := &variFlightDataServiceGetFlightDataByDepartureAndArrivalStatusClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VariFlightDataService_GetFlightDataByDepartureAndArrivalStatusClient interface {
	Recv() (*VariFlightData, error)
	grpc.ClientStream
}

type variFlightDataServiceGetFlightDataByDepartureAndArrivalStatusClient struct {
	grpc.ClientStream
}

func (x *variFlightDataServiceGetFlightDataByDepartureAndArrivalStatusClient) Recv() (*VariFlightData, error) {
	m := new(VariFlightData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// VariFlightDataServiceServer is the server API for VariFlightDataService service.
type VariFlightDataServiceServer interface {
	GetFlightDataByFlightNumber(*GetFlightDataByFlightNumberRequest, VariFlightDataService_GetFlightDataByFlightNumberServer) error
	GetFlightDataBetweenTwoAirports(*GetFlightDataBetweenTwoAirportsRequest, VariFlightDataService_GetFlightDataBetweenTwoAirportsServer) error
	GetFlightDataBetweenTwoCities(*GetFlightDataBetweenTwoCitiesRequest, VariFlightDataService_GetFlightDataBetweenTwoCitiesServer) error
	GetFlightDataByDepartureAndArrivalStatus(*GetFlightDataAtOneAirportByStatusRequest, VariFlightDataService_GetFlightDataByDepartureAndArrivalStatusServer) error
}

// UnimplementedVariFlightDataServiceServer can be embedded to have forward compatible implementations.
type UnimplementedVariFlightDataServiceServer struct {
}

func (*UnimplementedVariFlightDataServiceServer) GetFlightDataByFlightNumber(req *GetFlightDataByFlightNumberRequest, srv VariFlightDataService_GetFlightDataByFlightNumberServer) error {
	return status.Errorf(codes.Unimplemented, "method GetFlightDataByFlightNumber not implemented")
}
func (*UnimplementedVariFlightDataServiceServer) GetFlightDataBetweenTwoAirports(req *GetFlightDataBetweenTwoAirportsRequest, srv VariFlightDataService_GetFlightDataBetweenTwoAirportsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetFlightDataBetweenTwoAirports not implemented")
}
func (*UnimplementedVariFlightDataServiceServer) GetFlightDataBetweenTwoCities(req *GetFlightDataBetweenTwoCitiesRequest, srv VariFlightDataService_GetFlightDataBetweenTwoCitiesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetFlightDataBetweenTwoCities not implemented")
}
func (*UnimplementedVariFlightDataServiceServer) GetFlightDataByDepartureAndArrivalStatus(req *GetFlightDataAtOneAirportByStatusRequest, srv VariFlightDataService_GetFlightDataByDepartureAndArrivalStatusServer) error {
	return status.Errorf(codes.Unimplemented, "method GetFlightDataByDepartureAndArrivalStatus not implemented")
}

func RegisterVariFlightDataServiceServer(s *grpc.Server, srv VariFlightDataServiceServer) {
	s.RegisterService(&_VariFlightDataService_serviceDesc, srv)
}

func _VariFlightDataService_GetFlightDataByFlightNumber_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetFlightDataByFlightNumberRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VariFlightDataServiceServer).GetFlightDataByFlightNumber(m, &variFlightDataServiceGetFlightDataByFlightNumberServer{stream})
}

type VariFlightDataService_GetFlightDataByFlightNumberServer interface {
	Send(*VariFlightData) error
	grpc.ServerStream
}

type variFlightDataServiceGetFlightDataByFlightNumberServer struct {
	grpc.ServerStream
}

func (x *variFlightDataServiceGetFlightDataByFlightNumberServer) Send(m *VariFlightData) error {
	return x.ServerStream.SendMsg(m)
}

func _VariFlightDataService_GetFlightDataBetweenTwoAirports_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetFlightDataBetweenTwoAirportsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VariFlightDataServiceServer).GetFlightDataBetweenTwoAirports(m, &variFlightDataServiceGetFlightDataBetweenTwoAirportsServer{stream})
}

type VariFlightDataService_GetFlightDataBetweenTwoAirportsServer interface {
	Send(*VariFlightData) error
	grpc.ServerStream
}

type variFlightDataServiceGetFlightDataBetweenTwoAirportsServer struct {
	grpc.ServerStream
}

func (x *variFlightDataServiceGetFlightDataBetweenTwoAirportsServer) Send(m *VariFlightData) error {
	return x.ServerStream.SendMsg(m)
}

func _VariFlightDataService_GetFlightDataBetweenTwoCities_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetFlightDataBetweenTwoCitiesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VariFlightDataServiceServer).GetFlightDataBetweenTwoCities(m, &variFlightDataServiceGetFlightDataBetweenTwoCitiesServer{stream})
}

type VariFlightDataService_GetFlightDataBetweenTwoCitiesServer interface {
	Send(*VariFlightData) error
	grpc.ServerStream
}

type variFlightDataServiceGetFlightDataBetweenTwoCitiesServer struct {
	grpc.ServerStream
}

func (x *variFlightDataServiceGetFlightDataBetweenTwoCitiesServer) Send(m *VariFlightData) error {
	return x.ServerStream.SendMsg(m)
}

func _VariFlightDataService_GetFlightDataByDepartureAndArrivalStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetFlightDataAtOneAirportByStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VariFlightDataServiceServer).GetFlightDataByDepartureAndArrivalStatus(m, &variFlightDataServiceGetFlightDataByDepartureAndArrivalStatusServer{stream})
}

type VariFlightDataService_GetFlightDataByDepartureAndArrivalStatusServer interface {
	Send(*VariFlightData) error
	grpc.ServerStream
}

type variFlightDataServiceGetFlightDataByDepartureAndArrivalStatusServer struct {
	grpc.ServerStream
}

func (x *variFlightDataServiceGetFlightDataByDepartureAndArrivalStatusServer) Send(m *VariFlightData) error {
	return x.ServerStream.SendMsg(m)
}

var _VariFlightDataService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.VariFlightDataService",
	HandlerType: (*VariFlightDataServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetFlightDataByFlightNumber",
			Handler:       _VariFlightDataService_GetFlightDataByFlightNumber_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetFlightDataBetweenTwoAirports",
			Handler:       _VariFlightDataService_GetFlightDataBetweenTwoAirports_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetFlightDataBetweenTwoCities",
			Handler:       _VariFlightDataService_GetFlightDataBetweenTwoCities_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetFlightDataByDepartureAndArrivalStatus",
			Handler:       _VariFlightDataService_GetFlightDataByDepartureAndArrivalStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "variflight.proto",
}
