// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	"context"

	"github.com/ethereum/go-ethereum/common"

	"github.com/stretchr/testify/mock"
)

// ethClient is an autogenerated mock type for the ethClient type
type EthClient struct {
	mock.Mock
}

// PendingNonceAt provides a mock function with given fields: ctx, account
func (m *EthClient) PendingNonceAt(ctx context.Context, account common.Address) (uint64, error) {
	args := m.Called(ctx, account)
	return args.Get(0).(uint64), args.Error(1)
}
